# Generated by Django 5.1.6 on 2026-04-25 19:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("Company", "Company"), ("Contract", "Contract")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1024)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes.")),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("uploaded_by", models.UUIDField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-uploaded_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="core_docume_entity__5c543a_idx"
                    )
                ],
            },
        ),
    ]
