# Generated manually for W1-37 — soft-delete flag for document rows.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_document_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["entity_type", "entity_id", "is_active"],
                # Must match Django's autogenerated name so ``makemigrations --check`` passes in CI.
                name="core_docume_entity__a62b20_idx",
            ),
        ),
    ]
