# Generated by Django 5.1.6 on 2026-05-25 01:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In progress", "In progress"),
                            ("Waiting response", "Waiting response"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        db_index=True,
                        default="Open",
                        max_length=32,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_role", models.CharField(max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at", "-created_at", "subject"),
                "indexes": [
                    models.Index(
                        fields=["company_id", "status"],
                        name="core_ticket_company_status_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_user_id", models.UUIDField()),
                ("author_role", models.CharField(max_length=24)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["ticket_id", "created_at"],
                        name="core_tmsg_ticket_created_idx",
                    )
                ],
            },
        ),
    ]
