# Generated by Django 5.1.6 on 2026-05-25 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("space_id", models.UUIDField(db_index=True)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["company_id", "status"], name="cont_company_status_idx"
                    ),
                    models.Index(
                        fields=["space_id", "status"], name="cont_space_status_idx"
                    ),
                ],
            },
        ),
    ]
