# Generated by Django 5.1.6 on 2026-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="assigned_space_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="rental_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="equipmentassignment",
            name="assigned_space_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["assigned_space_id", "status"], name="inv_eq_space_status"),
        ),
    ]
