# Generated by Django 5.1.6 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_equipment_assigned_space_id_equipment_rental_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="rental_cost_unit",
            field=models.CharField(
                choices=[("hour", "Per hour"), ("day", "Per day"), ("fixed", "Fixed per booking")],
                default="hour",
                max_length=16,
            ),
        ),
    ]
