# Generated by Django 5.1.6 on 2026-05-25 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("space_id", models.UUIDField(db_index=True)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                ("created_by_role", models.CharField(blank=True, max_length=24)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("quoted_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("equipment_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["company_id", "status"],
                        name="booking_company_status_idx",
                    ),
                    models.Index(
                        fields=["space_id", "status"], name="booking_space_status_idx"
                    ),
                    models.Index(
                        fields=["is_public", "status"], name="booking_public_status_idx"
                    ),
                ],
            },
        ),
    ]
