# Generated by Django 5.1.6 on 2026-05-25 02:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_id", models.UUIDField(unique=True)),
                ("company_id", models.UUIDField(db_index=True)),
                ("space_id", models.UUIDField()),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_sqm", models.DecimalField(decimal_places=2, max_digits=12)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("company_id", "contract_id"),
                "indexes": [
                    models.Index(
                        fields=["company_id", "is_active"],
                        name="bcontract_company_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("contract_id", models.UUIDField(blank=True, null=True)),
                ("booking_id", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("contract", "contract"), ("booking", "booking")],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("overdue", "overdue"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("reference_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["company_id", "status"], name="pay_company_status_idx"),
                    models.Index(
                        fields=["contract_id", "period_start"],
                        name="pay_contract_period_idx",
                    ),
                    models.Index(fields=["booking_id", "source"], name="pay_booking_source_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(max_length=128)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-processed_at",),
                "indexes": [
                    models.Index(fields=["event_type"], name="core_processed_event_type_idx")
                ],
            },
        ),
    ]
