# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("monthly", "monthly"), ("rental", "rental")],
                db_index=True,
                default="monthly",
                max_length=16,
            ),
        ),
    ]
