# Generated by Django 5.1.6 on 2026-05-25 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_space_model_and_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-processed_at",),
            },
        ),
        migrations.CreateModel(
            name="SpaceBookingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_id", models.UUIDField(db_index=True, unique=True)),
                ("company_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        db_index=True,
                        default="Approved",
                        max_length=24,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("equipment_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-start_time", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SpaceContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_id", models.UUIDField(db_index=True, unique=True)),
                ("company_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Terminated", "Terminated"),
                        ],
                        max_length=24,
                    ),
                ),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("termination_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RenameIndex(
            model_name="space",
            new_name="space_is_active_idx",
            old_name="core_space_is_active_idx",
        ),
        migrations.AddField(
            model_name="space",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="space",
            name="company_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Maintenance", "Maintenance"),
                    ("Blocked", "Blocked"),
                ],
                db_index=True,
                default="Available",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="spacebookingrecord",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.space",
            ),
        ),
        migrations.AddField(
            model_name="spacecontract",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="core.space",
            ),
        ),
        migrations.AddIndex(
            model_name="spacetype",
            index=models.Index(fields=["is_active"], name="space_type_active"),
        ),
        migrations.AddField(
            model_name="space",
            name="space_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spaces",
                to="core.spacetype",
            ),
        ),
        migrations.AddIndex(
            model_name="space",
            index=models.Index(
                fields=["company_id", "is_active"], name="space_company_active"
            ),
        ),
        migrations.AddIndex(
            model_name="space",
            index=models.Index(fields=["status"], name="space_status_idx"),
        ),
        migrations.AddIndex(
            model_name="spacebookingrecord",
            index=models.Index(
                fields=["space", "status"], name="space_book_space_status"
            ),
        ),
        migrations.AddIndex(
            model_name="spacebookingrecord",
            index=models.Index(
                fields=["company_id", "status"], name="space_book_company_status"
            ),
        ),
        migrations.AddIndex(
            model_name="spacecontract",
            index=models.Index(
                fields=["company_id", "status"], name="space_contract_c_status"
            ),
        ),
        migrations.AddIndex(
            model_name="spacecontract",
            index=models.Index(
                fields=["space", "status"], name="space_contract_s_status"
            ),
        ),
    ]
