# Generated by Django 5.1.6 on 2026-05-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_space_service_extensions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecontract",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="space",
            name="core_space_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="spacecontract",
            name="core_space_contract_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="spacecontract",
            name="core_space_contract_status_idx",
        ),
        migrations.AlterField(
            model_name="space",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("blocked", "Blocked")],
                db_index=True,
                default="available",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="spacebookingrecord",
            name="booking_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="spacebookingrecord",
            name="state",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="spacecontract",
            name="company_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="spacecontract",
            name="contract_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="spacecontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("terminated", "Terminated"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
