# Generated by Django 5.1.6 on 2026-05-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_space_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("Occupied", "Occupied"),
                    ("Maintenance", "Maintenance"),
                    ("Blocked", "Blocked"),
                ],
                db_index=True,
                default="Available",
                max_length=24,
            ),
        ),
    ]
