# Generated by Django 5.1.6 on 2026-05-27

from decimal import Decimal

from django.db import migrations, models

STUB_SPACE_PRICES: tuple[tuple[str, Decimal, str], ...] = (
    ("22222222-2222-4222-8222-222222222201", Decimal("18.00"), "hour"),
    ("22222222-2222-4222-8222-222222222202", Decimal("95.00"), "day"),
    ("22222222-2222-4222-8222-222222222203", Decimal("30.00"), "hour"),
)


def seed_stub_space_prices(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    Space = apps.get_model("core", "Space")
    db_alias = schema_editor.connection.alias
    for space_id, rental_cost, rental_cost_unit in STUB_SPACE_PRICES:
        Space.objects.using(db_alias).filter(id=space_id).update(
            rental_cost=rental_cost,
            rental_cost_unit=rental_cost_unit,
        )


def clear_stub_space_prices(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    Space = apps.get_model("core", "Space")
    db_alias = schema_editor.connection.alias
    Space.objects.using(db_alias).filter(
        id__in=[space_id for space_id, _rental_cost, _rental_cost_unit in STUB_SPACE_PRICES],
    ).update(rental_cost=None, rental_cost_unit="hour")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_space_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="rental_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="rental_cost_unit",
            field=models.CharField(
                choices=[("hour", "Per hour"), ("day", "Per day"), ("fixed", "Fixed per booking")],
                default="hour",
                max_length=16,
            ),
        ),
        migrations.RunPython(seed_stub_space_prices, clear_stub_space_prices),
    ]
