# Generated by Django 5.1.6 on 2026-05-25 03:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProjection",
            fields=[
                ("company_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "cae_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "maturity_stage_name",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "company_id"),
            },
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-processed_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingProjection",
            fields=[
                ("booking_id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("space_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(db_index=True, max_length=24)),
                (
                    "quoted_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "space_id"],
                        name="dash_booking_status_space_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractProjection",
            fields=[
                ("contract_id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_id", models.UUIDField(db_index=True)),
                ("space_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "area_sqm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rate_per_sqm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=24),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["space_id", "is_active"],
                        name="dash_contract_space_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProjection",
            fields=[
                ("employee_id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_id", models.UUIDField(db_index=True)),
                (
                    "employee_type",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company_id", "is_active"],
                        name="dash_emp_company_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentProjection",
            fields=[
                ("payment_id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("contract_id", models.UUIDField(blank=True, null=True)),
                ("booking_id", models.UUIDField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("paid_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company_id", "paid_at"],
                        name="dash_payment_company_paid_idx",
                    )
                ],
            },
        ),
    ]
