"""Create Employee model."""

# Generated by Django 5.1.6 on 2026-05-08 01:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_company_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Intern", "Intern"),
                            ("PhD", "PhD"),
                            ("Designer", "Designer"),
                            ("Junior", "Junior"),
                            ("Senior", "Senior"),
                        ],
                        max_length=32,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ("company", "name"),
                "indexes": [
                    models.Index(fields=["company_id"], name="core_employee_company_id_idx"),
                    models.Index(fields=["is_active"], name="core_employee_is_active_idx"),
                    models.Index(fields=["type"], name="core_employee_type_idx"),
                ],
            },
        ),
    ]
